# Generated by Django 5.1.2 on 2024-10-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblog',
            name='image',
            field=models.ImageField(default='images/default_image.jpg', upload_to='images/'),
            preserve_default=False,
        ),
    ]
