# Generated by Django 5.0.3 on 2024-10-09 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_myblog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myblog',
            name='image',
        ),
    ]
