# Generated by Django 5.0.3 on 2024-10-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_remove_myblog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
