# Generated by Django 5.0.3 on 2024-10-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0010_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.URLField(blank=True, default='exit', max_length=500),
            preserve_default=False,
        ),
    ]
